### ISSUE TITLE
Expand Profile-Customizable Elements

### ISSUE THREAD

**Issue by DavidRies** [scapcommunity/XCCDF#16]
Allow more more elements to be customized via profile (and Tailoring):

- Customizing the XCCDF metadata (titles, descriptions, etc.)
- Adding external rules and/or checks
- Overriding arbitrary OVAL elements and/or values

**Comment by joesain26** [comment]
This issue is covered in the scapcommunity/authoring repo, Enhanced Content Execution Control (https://github.com/scapcommunity/authoring/issues/4). Closing it here.

**Comment by DavidRies** [comment]
It seems to me that this belongs in this group. I'm not sure what this has to do with Authoring. This has to do with run-time customization. This requires a spec change. I thought the authoring group was focussed on creating tools for authoring content, not spec changes.

**Comment by joesain26** [comment]
Reopened!

**Comment by DavidRies** [comment]
I've created a document capturing some high-level ideas for approaching this issue. Please see: https://github.com/scapcommunity/XCCDF/blob/master/working-documents/expand-profile-customization.md

**Comment by redhatrises** [comment]
> I've created a document capturing some high-level ideas for approaching this issue. Please see: https://github.com/scapcommunity/XCCDF/blob/master/working-documents/expand-profile-customization.md

PRs are best for comments. ;)

A couple of things:

1. `prohibitChanges` shouldn't be able to be changed in tailoring or allowed to be overrided.
2. Not sure that `hidden` or `interactive` should be overrided either
3. In many cases, `selector` can already be overridden in tailoring.
4. Shouldn't `Refine-Referenced-Check-Content` be `Refine-Check` like the other refine elements?
5. How is the determination of replacement vs append going to happen? For example, if there is a regulatory warning added, should there exist a capability to completely replace that warning? Seems like that shouldn't be allowed.

**Comment by DavidRies** [comment]
Thanks, Gabe. There's a good conversation to have around what *shouldn't* be Tailorable.  

In the conversation-starter, I err'd on the side of making everything Tailorable unless it just wasn't cogent (e.g. `signature`, `@resolved`) or would introduce significant XCCDF-internal technical side-effects (e.g. `@id`).

My thinking was as follows. XCCDF Benchmarks are text documents ("open source"). Right now (and no matter what changes we make or don't make), anyone can modify anything by simply editing the document. And, downstream "re-users" of content might have good reasons to change things. For example, a Rule might be `@hidden=true` because it's incomplete and the check-content hasn't been written. It might be an important Rule for my organization, so we might write the check content and want to set `@hidden=false` so we can run it.

With that in mind, it might make more sense to reframe this as a concern about provenance. We don't want someone thinking that assessment results represent the "Official OrgFoo-Sanctified Benchmark" when, in fact, they have been Tailored into something substantively different than what the original author intended. And, we have some capabilities in place to help with this already. The original document can be signed. And, the Tailorings can be signed. And Tailorings are already included in ARF results and indicated in XCCDF results.

If we go this route, we should think about the following:
- Do assessment results from Tailored Benchmarks indicate that they have been Tailored with sufficient clarity and detail?
- Do we want to require Tailorings to have some additional provenance information (e.g. author, org, etc.) that we also require in result formats?
- Would it be valuable to differentiate between 2 different "styles" of Tailoring: 
   1. Limited Tailoring: something like the current Tailoring capabilities that limit the scope of customization to within the original authors intent. The results of a "Limited Tailored" scan would still be considered an "Official" Benchmark result.
   2. Customization: something like the full set of capabilities [proposed here](https://github.com/scapcommunity/XCCDF/blob/master/working-documents/expand-profile-customization.md). The results of a "Customized" scan would be considered something new/different from the original content and indicated as such in result documents.

-David

**Comment by bgro** [comment]
A distinction of "limited tailoring" and "customizing" sounds tempting, but  I fear is not always easy to mark a borderline between the two.

Can we actually say even for the existing tailoring mechanism, that a tailored scan would be a an "Official" Benchmark result? After all, using even only existing tailoring mechanisms, I can reduce the number of selected rules to any subset I like and I can (if the author has provided values for parameterization) set values to completely insecure values. Thus I have an "Official" Benchmark result for a completely insecure system...

Maybe a distinction can be seen in some of Gabe's reservations about certain modification capbabilites: if you do limited tailoring, you should. roughly speaking, not be able to replace things but only to add to things? 

Some thoughts about features for tailoring:

- Maybe an additional  feature for "full customization" would be the specifcation of a schema how
  identifiers should be rewritten, essentially moving the customized document into a different
  namespace?

- What about adding content, e.g. adding rules? That might even be considered "limited tailoring" 
  (with the rule IDs in a different namespace): use the CIS XYZ benchmark but add a couple of rules 
  which are important in my environment...

- If limited tailoring at least for certain fields only allows additions, we might want to distinguish
  between prepending and appending content.

**Comment by DavidRies** [comment]
Notes from the 5/7/20 call related to this Issue (from several including Bernd and Adam!):

- Consider making this a new capability, separate from xccdf:Profile & xccdf:Tailoring (call it a "customization" or "import" or something else TBD)
- Add the capability to add new xccdf:Groups and xccdf:Rules

Make it very clear that scans have used a "customized" benchmark:

- Require a new ID namespace that gets applied to the xccdf IDs when the customization is used (i.e. all the xccdf IDs change to reflect customization)
- Consider also requiring a title (that would override Benchmark title), benchmark id/version, author, etc.
- Consider requiring that usage of this "customization" file requires generation of a new Benchmark. This might mean creating a new file with the customizations applied. Or, perhaps, it would mean applying the customizations and generating reports based on that.

I'd love any clarifications and additional feedback on this Issue!

**Comment by bgro** [comment]
The notes capture the essence of the discussion very well, thank you for the summary! 

What might be a useful requirement / feature is that when a customization is carried out, in the result (be that a generated benchmark file or the results-file generated by the SCAP-scanner) each rule would automatically carry a backward-reference to the rule from which it originated. Depending on how the new IDs are constructed, such information might also be derivable from the IDs, but we may want to provide the "customizer" more freedom in how to rewrite IDs. So adding a backward-reference would be on the safe side.

By the way, regarding the terms: I would prefer "customization" over "import".

**Comment by DavidRies** [comment]
Hello All, 

I have been working on this proposal and wanted to provide an update in advance of our call today.

First of all, I made revisions to reflect the feedback, creating a new capability "XCCDF Extension" which would be additive, leaving Profiles and Tailoring unchanged. 

Working through the details, the proposal has become complex. There are currently 20 new XCCDF elements, each with their own attributes and children, as well as a myriad of processing and inheritance rules, etc.  We workshopped the idea around the whiteboard and are concerned:
- it's overly complicated making it non-trivial to implement, author and read without specialized tooling
- even with LRIs and rule-specific changelogs, it's not clear that this approach will significantly simply the process of migrating content customizations from one version of a Benchmark to the next without specialized tooling

Ultimately, the migration problem is a really a "merge" (in the Git/software sense of joining together two versions of a codebase). And... merges suck. Even with the best available tooling, software developers work hard to avoid non-trivial merges.

Coincidentally, here at Joval we are currently working on a project which requires us to migrate Benchmark changes from old versions of several Benchmarks to new versions. We are going to use this project to try out several approaches and apply what we learn to this Issue.

-David

**Comment by DavidRies** [comment]
I went ahead and updated the [Conversation Starter](https://github.com/scapcommunity/XCCDF/blob/master/working-documents/expand-profile-customization.md) to reflect what we are working through internally.

**Comment by DavidRies** [comment]
As per our discussion today, we are inclined to abandon this issue. The primary goal was to better support migration of customizations to a benchmark across and we don't think that this schema change will help us achieve that goal.

**Comment by DavidRies** [comment]
in the absence of feedback to the contrary, closing this issue.
