### ISSUE TITLE
Validating provenance of remotely referenced content

### ISSUE THREAD

**Issue by cmschmidt** [scapcommunity/XCCDF#34]
There is a desire to support references to remote content within XCCDF benchmarks. This would be content that resided at an accessible internet address rather than being bundled with the benchmark. When an assessment is run, the external references would be resolved and the relevant content downloaded automatically. However, as said content would be outside of the control of the party that downloaded the benchmark, there is interest in developing capabilities to allow the source and integrity of this external content to be validated before the content is used in an assessment. (This issue came out of issue #2 )

**Comment by cmschmidt** [comment]
# Proposal for Remote Check Reference Provenance

# Background

The community wants to support references to remote content within XCCDF checks. The community wishes to add capabilities to allow integrity checking of the remotely referenced content. Since the goal of using remote content is to allow that content to change (e.g., references to an evolving list of vulnerability checks), integrity cannot be verified through comparison to a hash value within the XCCDF document as that hash value would be out of date as soon as the remotely referenced file changed. Instead, the proposal is to ensure that changes to the remotely referenced file are only made by a trusted party.

# Proposal Overview

The proposal is to allow the authors of the XCCDF content that makes remote reference to specify the identity of the party that &quot;secures&quot; the remotely referenced content. &quot;Securing&quot; the content can be done in one of two ways:

1. A party can secure content by delivering it over an encrypted channel, such as HTTPS using TLS, where the identity of the party serving the content is authenticated. The authenticated identity becomes the identity of the securing party.
2. A party can secure content by including a digital signature with that content. Any type and format of digital signature may be used provided that it identifies the signing party and ensures that any changes to the content after signing will be detectable. The receiving party must check that the content has not changed since it was signed and must check that the signing certificate is part of a verified certification chain to a trusted root CA. The identity of the party that signed the content is the securing party.

In option 1, the fact that the content was received from the indicated remote source and that source was authenticated is sufficient to meet the threshold to assert that the content is trusted. This is, however, not equivalent to the level of trust provided in option 2 since option 1 can only assert that the content was received from a trusted party while option 2 allows one to assert that the content has not been altered by anyone since it was signed by a trusted party. However, option 1 requires less work by both the content author and the content consumer and will likely be seen as providing adequate assurance for most users. Through the use of parameters in the content, the XCCDF author will be able to control which of these two options are used.

# Technical Details

It is assumed that the XCCDF check-content-ref will be used to reference external content. It is further assumed that this will be done by placing the external location of the content to gather in the href attribute.

It is proposed that a new &quot;check-secured&quot; attribute be added. This attribute has a Boolean value with a default value of false.

It is proposed that a new &quot;accepted-signer&quot; element be added that is a child element of check-content-ref. Zero or more instances of this element can appear. accepted-signer has no attributes and its body consists only of a string. The value of the string is the identity of a party as it would appear in a signing certificate. (Different types of certificates might use different fields as the identity. The final specification will need to enumerate acceptable certificate types and the specific field or fields that are compared against the value of an accepted-signer element.)

When processing a check-content-ref, one of the following three options might occur:

1. If check-secured is false, the check-content-ref is processed per the current XCCDF procedures without any validation of the content source. Any accepted-signer children of this check-content-ref are ignored.
2. If check-secured is true and there are no accepted-signer children of this check-content-ref, then when the system attempts to resolve the reference it MUST authenticate the source of the content.
  1. Authentication will automatically fail if the source is local or if it is transmitted over a protocol that does not support server authentication (e.g., if the content is sent over http rather than https).
  2. If the source cannot be successfully authenticated, then this is treated as a failure to resolve the current check-content-ref, per the Check.Content step of XCCDF processing, which would lead to the next check-content-ref or check-content element being attempted within the Rule.
  3. The XCCDF parser MAY cache prior retrievals of content so that frequently-referenced content does not need to be downloaded multiple times. If the content is successfully authenticated when it is retrieved, then the cached content is treated as having its source successfully authenticated for later references without requiring the full network authentication process to be done each time. However, note that it is possible that some content might be initially downloaded for a check-content-ref that did not require authentication but that a later check-content-ref to the same external content might require authentication. In this case, the parser MUST ignore the cached content whose source was not authenticated and retrieve the external content again, this time performing authentication of the source. Tools might wish to compile a list of all external content requiring source authentication and download them all once with source authentication to avoid the possibility of duplicative downloads.
  4. The XCCDF parser SHOULD consult relevant certificate revocation lists while authenticating the source of the external content.
3. If check-secured is true and there are accepted-signer children in this check-content-ref, then when the system attempts to resolve the reference it MUST validate and confirm the provenance of this content.
  1. This method does not require the content in question to be delivered over a secure protocol. The referenced content can also be local.
  2. If the content is not cryptographically signed in a manner that can understood by the XCCDF parser, then the attempt to resolve the reference automatically fails.
  3. If the content is cryptographically signed in a manner that can be understood by the XCCDF parser, then the parser MUST validate and confirm the provenance of the content by doing the following:
    1. Verify that the identity of the signer, as indicated by the signing certificate matches one of the values of an accepted-signer element within this check-content-ref. It does not matter how many accepted-signer values do not match as long as at least one matches the identity of the signing certificate owner.
    2. Verify that the public signing certificate is valid and uncorrupted and that it belongs to a certificate trust chain rooted in a trusted certificate authority. (The parsers determine which certificate authorities, and certificates therefrom, are trusted. This should be configurable.) The tool SHOULD consult appropriate certificate revocation lists during this step.
    3. Verify that the cryptographic signature was actually created by the identified signer by validating it using the public signing certificate.
    4. Verify that the content file matches the value in the signature. (I.e., the integrity of the file is intact.)
  4. If any step in the attempt to validate and confirm the provenance of the content fails, then this check-content-ref is treated as failing to resolve.
  5. XCCDF parsers MAY cache the results of attempting to validate and confirm a piece of content. However, when doing so, it is important to record which signer was used to validate and confirm the content. This is because it is possible (although highly unlikely) that two check-content-refs in a single XCCDF document might have different lists of accepted signers.

When dealing with cached content, the two methods of validating the provenance of the content are not equivalent. As such, content whose source was validated cannot automatically be treated as having its provenance validated and confirmed. Similarly, validating and confirming the provenance of content does not automatically convey that its source was authenticated. As such, when caching content it is important to note what, if any, authentication and provenance checking has been done on that content.

XCCDF tools SHOULD NOT retain caches of retrieved content that last longer than a single assessment. This is because, as noted before, a major use case of externally referenced content is to allow that content to change. Retaining caches of externally referenced content for long periods of time could prove counter-productive to that goal.

**Comment by solind** [comment]
I am wondering if it isn't a little bit strange for the original content author to act as the specification-declared authority relating to the validation of externally-linked content.  Generally speaking, with currently-existing tools, an operator decides whether or not to enable or disable things like signature validation at run-time.  It seems to me that the operator is the one who should be primarily concerned with the security and authenticity of the content that's being used, not the author.

I also want to note that content may have relative externally-linked content, and this procedure seems to ignore this possibility, which has many possible side-effects.  For example, is there really a need to cache or validate content that's already on a local drive, being accessed via a file:// URL?  There is also the matter of protocol-level caching that may be in-play.  Caching may not be up to the XCCDF parser, there might be a caching firewall (including a caching reverse-SSL proxy, for example -- which may itself cause its own problems).

Just some more food for thought.

**Comment by djhaynes** [comment]
There is not strong community demand for this proposal so the group decided to close the issue during the 8/20 teleconference.
